# Generated by Django 3.1.7 on 2021-04-08 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('total_qs', models.IntegerField()),
                ('Obtained_marks', models.IntegerField()),
                ('Percentage', models.FloatField()),
                ('feedback', models.CharField(max_length=200)),
                ('improvement_feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tests',
            fields=[
                ('test_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=100)),
                ('test_no', models.IntegerField()),
                ('test_file', models.FileField(upload_to='uploads/')),
                ('grades_file', models.FileField(upload_to='uploads/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_roll_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.student')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.tests')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
