# Generated by Django 3.1.7 on 2021-04-08 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0002_auto_20210408_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='grades',
            new_name='Grade',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='tests',
            new_name='Test',
        ),
    ]
