# Generated by Django 3.1.7 on 2021-04-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_delete_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
