# Generated by Django 3.1.7 on 2021-04-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20210408_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
